import './globals.css'
import localFont from 'next/font/local'

const generalSans = localFont({
  src: [
    {
      path: '../fonts/GeneralSans-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../fonts/GeneralSans-Medium.otf',
      weight: '500',
      style: 'normal',
    },
  ],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={generalSans.className}>{children}</body>
    </html>
  )
}
